sonar.projectKey=teaching-action_plugins-development_service-schema_local_serviceschema_11bf4ccf-131d-48e5-9054-9437db8311ba
sonar.projectName=Local Service Schema
sonar.projectVersion=2026020205

sonar.exclusions=amd/build/**,coverage/**,tests/**,extlib/**,thirdpartylibs.xml,lang/**
sonar.qualitygate.wait=true