#!/bin/bash
# Create git tag based on extracted version information
# Author: Hector Arrechea <hector.arrechea@ct.uneatlantico.es>

set -e

echo "=== Version Tag Creation ==="

# Read version info from dotenv (preferred) or fallback to files
if [ -z "$TAG_NAME" ]; then
    if [ -f "tag_name.txt" ]; then
        TAG_NAME=$(cat tag_name.txt)
        RELEASE=$(cat release.txt)
        MATURITY=$(cat maturity.txt)
    else
        echo "❌ Error: Version information not found!"
        exit 1
    fi
fi

echo "📦 Release: $RELEASE"
echo "🏷️  Maturity: $MATURITY"
echo "🔖 Tag: $TAG_NAME"
echo ""

# Fetch all tags from remote
echo "Fetching existing tags..."
git fetch --tags

# Check if tag already exists locally
if git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
    echo "ℹ️  Tag '$TAG_NAME' already exists locally. Skipping creation."
    exit 0
fi

# Check if tag exists remotely but not locally
if git ls-remote --tags origin | grep -q "refs/tags/$TAG_NAME"; then
    echo "ℹ️  Tag '$TAG_NAME' exists remotely. Skipping creation."
    exit 0
fi

# Create and push new tag
echo ""
echo "🚀 Creating new tag: $TAG_NAME"

# Get commit info for tag message
COMMIT_TITLE=$(git log -1 --pretty=format:"%s")
COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
COMMIT_DATE=$(git log -1 --pretty=format:"%ci")

TAG_MESSAGE="Release $TAG_NAME

Release: $RELEASE
Maturity: $MATURITY
Commit: ${CI_COMMIT_SHORT_SHA:-$(git rev-parse --short HEAD)}
Author: $COMMIT_AUTHOR
Date: $COMMIT_DATE

Latest commit: $COMMIT_TITLE

Auto-generated by GitLab CI/CD Pipeline
Pipeline: ${CI_PIPELINE_URL:-N/A}"

# Create annotated tag
COMMIT_SHA="${CI_COMMIT_SHA:-HEAD}"
git tag -a "$TAG_NAME" -m "$TAG_MESSAGE" "$COMMIT_SHA"

# Push tag to remote
echo "Pushing tag to remote..."
if git push origin "$TAG_NAME" 2>&1; then
    echo ""
    echo "✅ Tag '$TAG_NAME' created and pushed successfully!"

    if [ -n "$CI_PROJECT_URL" ]; then
        echo "🔗 View tag: ${CI_PROJECT_URL}/-/tags/$TAG_NAME"
    fi
    exit 0
else
    PUSH_EXIT_CODE=$?
    echo ""
    echo "❌ Failed to push tag to remote (exit code: $PUSH_EXIT_CODE)"
    echo ""
    echo "📋 Troubleshooting:"
    echo "   1. Check repository settings:"
    echo "      Settings > Repository > Protected tags"
    echo "      Allow 'Maintainers' to create protected tags"
    echo ""
    echo "   2. Enable CI_JOB_TOKEN write access:"
    echo "      Settings > CI/CD > Token Access"
    echo "      Enable 'Allow CI job tokens to push to this repository'"
    echo ""
    echo "   3. Or add a PROJECT_ACCESS_TOKEN variable:"
    echo "      Settings > CI/CD > Variables"
    echo "      Add variable: PROJECT_ACCESS_TOKEN"
    echo "      With 'api' or 'write_repository' scope"
    echo ""
    echo "   4. Or use a GITLAB_TOKEN (Personal Access Token)"
    echo ""
    echo "ℹ️  Tag created locally but not pushed to remote."
    echo "   You can manually push it with: git push origin $TAG_NAME"

    # Exit with error code but allow pipeline to continue (allow_failure: true)
    exit 1
fi

